// Dev tool: fetch the latin-subset woff2 for the report's fonts from Google
// Fonts and emit sources/fonts.css with base64 data: URIs, so the generated
// report stays fully self-contained (zero external requests at view time).
// Re-run only when the font families/weights in style.css change.
//   node fetch-fonts.mjs
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(SCRIPT_DIR, "sources", "fonts.css");

// Families + weights actually referenced in style.css. zapac identity:
// Lato (display + body, AA Zuehlke fallback — proprietary, not distributable)
// + JetBrains Mono (code). Lato has no 600 weight; 400/700 cover the stack.
const SPEC =
  "family=Lato:wght@400;700" +
  "&family=JetBrains+Mono:wght@400;600;700";
const CSS_URL = `https://fonts.googleapis.com/css2?${SPEC}&display=swap`;
// Modern-browser UA so Google serves woff2 (not ttf).
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/124.0 Safari/537.36";

// The base-latin subset block carries this unicode-range; keep only that one.
const LATIN_MARK = "U+0000-00FF";

async function main() {
  const css = await (await fetch(CSS_URL, { headers: { "User-Agent": UA } })).text();
  const blocks = css.split("@font-face").slice(1);
  const out = [
    "/* Generated by fetch-fonts.mjs — latin-subset woff2, base64-inlined.",
    " * Self-hosted so the report makes zero external requests. Do not hand-edit. */",
  ];
  const URANGE =
    "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC," +
    "U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD";
  // These families are variable fonts — Google serves one identical woff2 per
  // requested weight. Dedupe by content so we embed each file once and cover the
  // weights with a font-weight range.
  const faces = new Map(); // key `${fam}|${style}|${b64}` -> {fam,style,b64,size,wghts:Set}
  for (const raw of blocks) {
    const b = raw.slice(0, raw.indexOf("}") + 1);
    if (!b.includes(LATIN_MARK)) continue; // skip cyrillic/greek/viet/latin-ext
    const fam = (b.match(/font-family:\s*'([^']+)'/) || [])[1];
    const wght = (b.match(/font-weight:\s*(\d+)/) || [])[1];
    const style = (b.match(/font-style:\s*(\w+)/) || [])[1] || "normal";
    const url = (b.match(/url\(([^)]+\.woff2)\)/) || [])[1];
    if (!fam || !wght || !url) continue;
    const buf = Buffer.from(await (await fetch(url)).arrayBuffer());
    const b64 = buf.toString("base64");
    const key = `${fam}|${style}|${b64}`;
    if (!faces.has(key)) faces.set(key, { fam, style, b64, size: buf.length, wghts: new Set() });
    faces.get(key).wghts.add(+wght);
  }
  let kept = 0;
  for (const { fam, style, b64, size, wghts } of faces.values()) {
    const ws = [...wghts].sort((a, b) => a - b);
    const weight = ws.length > 1 ? `${ws[0]} ${ws[ws.length - 1]}` : `${ws[0]}`;
    out.push(
      `@font-face{font-family:'${fam}';font-style:${style};font-weight:${weight};` +
        `font-display:swap;` +
        `src:url(data:font/woff2;base64,${b64}) format('woff2');` +
        `unicode-range:${URANGE};}`
    );
    kept++;
    console.error(`  ${fam} ${weight} ${style} — ${(size / 1024).toFixed(1)}KB`);
  }
  fs.writeFileSync(OUT, out.join("\n") + "\n", "utf-8");
  const kb = (fs.statSync(OUT).size / 1024).toFixed(0);
  console.error(`\nwrote ${kept} faces -> ${OUT} (${kb}KB)`);
}

main().catch((e) => {
  console.error("fetch-fonts failed:", e.message);
  process.exit(1);
});
