// One-command first-time setup: generate .env (if absent) + pnpm install + pnpm start.
// The daemon has NO baked-in defaults — this script materializes sensible ones
// into .env so a vanilla clone boots. Existing .env is NEVER clobbered (secrets).
// Stdlib only; no deps. Run: `pnpm bootstrap` (or `node scripts/bootstrap.mjs`).
import { existsSync, writeFileSync } from 'node:fs'
import { execFileSync, spawnSync } from 'node:child_process'
import { homedir, platform } from 'node:os'
import { join } from 'node:path'

const repoRoot = process.cwd()
const envPath = join(repoRoot, '.env')

if (existsSync(envPath)) {
  console.log('.env exists — skipping generation. Run `pnpm start`.')
  process.exit(0)
}

// --- CLAUDE_BIN detection (best-effort, cross-platform) ---
// node-pty on Windows does no PATH resolution, so CLAUDE_BIN must be absolute.
// We try `where`/`which` first, then common install locations. First hit wins.
function toFwd(p) { return p.replace(/\\/g, '/') }
function detectClaudeBin() {
  const isWin = platform() === 'win32'
  const candidates = []
  const lookup = isWin ? 'where' : 'which'
  try {
    const out = execFileSync(lookup, ['claude'], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] })
    const first = out.split(/\r?\n/).find(l => l.trim())
    if (first) candidates.push(first.trim())
  } catch { /* lookup binary absent or claude not on PATH */ }
  const home = homedir()
  if (isWin) {
    const localAppData = process.env.LOCALAPPDATA
    candidates.push(join(home, '.claude', 'local', 'claude.exe'))
    if (localAppData) candidates.push(join(localAppData, 'Programs', 'claude', 'claude.exe'))
  } else {
    candidates.push(join(home, '.claude', 'local', 'claude'))
    candidates.push('/usr/local/bin/claude')
    candidates.push('/opt/homebrew/bin/claude')
  }
  for (const c of candidates) if (c && existsSync(c)) return toFwd(c)
  return null
}

const claudeBin = detectClaudeBin()
const singHome = toFwd(join(homedir(), '.singularity'))
const claudeLine = claudeBin || '/absolute/path/claude.exe'

// claude-code-usage-report skill (bundled in-repo). stats.mjs is the CLI Singularity
// spawns for the spend report; reports land in the skill's default state root.
const usageSkill = join(repoRoot, '.claude', 'skills', 'claude-code-usage-report', 'scripts', 'stats.mjs')
const usageReports = join(homedir(), '.agents', '.claude-code-usage-report', 'reports')

const envContent = `# Singularity daemon config — generated by scripts/bootstrap.mjs
# Edit by hand; rerunning bootstrap will NOT clobber this file.

# REQUIRED — app state root (state/ + cache/ live here). No daemon default.
SINGULARITY_HOME=${singHome}

# REQUIRED — loopback port the Fastify + ws daemon binds (127.0.0.1 only).
PORT=4317

# REQUIRED — absolute path to the claude binary. No PATH fallback (Windows node-pty
# does no PATH resolution). If detection failed, the placeholder below must be fixed.
CLAUDE_BIN=${claudeLine}

# OPTIONAL — absolute path to the ollama binary. Absent → ollama models unavailable.
#OLLAMA_BIN=

# OPTIONAL — trusted root for .worktrees/ + .tickets/ (default = this clone).
# Set for a global/npx install where the clone isn't writable.
#SING_TRUSTED_ROOT=

# OPTIONAL — skill-scopes root (author-specific layout). Absent → no skill-scopes;
# the skills viewer auto-detects flat (~/.claude/skills + <project>/.claude/skills).
#SING_SCOPE_ROOT=

# OPTIONAL (claude-code-usage-report skill) — absent = spend/usage-report degrade silently.
# Filled to the bundled in-repo skill; bootstrap also wires its statusline (see below).
SING_USAGE_SKILL=${toFwd(usageSkill)}
SING_USAGE_REPORTS=${toFwd(usageReports)}

# OPTIONAL — shared-secret token gating data endpoints + WS (x-sing-token / ?token=).
#SING_TOKEN=
`

writeFileSync(envPath, envContent, 'utf8')
console.log(`Generated .env at ${envPath}`)
console.log(`  SINGULARITY_HOME=${singHome}`)
console.log(`  PORT=4317`)
console.log(`  CLAUDE_BIN=${claudeLine}`)
if (!claudeBin) {
  console.warn('\nWARNING: could not detect claude binary. Edit CLAUDE_BIN in .env to an absolute path before `pnpm start`.')
}

// Wire the usage-report skill: SessionEnd hook + statusline into ~/.claude/settings.json
// (idempotent; skips a statusline you already have). Best-effort — a vanilla clone may
// lack the skill, or the global settings write may fail; never abort bootstrap over it.
if (existsSync(usageSkill)) {
  console.log('\nInstalling claude-code-usage-report (SessionEnd hook + statusline)…')
  const usage = spawnSync(process.execPath, [usageSkill, 'install', '--with-statusline'], { stdio: 'inherit' })
  if (usage.status !== 0) {
    console.warn(`\nWARNING: usage-report install skipped (exit ${usage.status ?? 'spawn error'}). `
      + `Per-session $ will be blank until wired. Run by hand:\n  node "${usageSkill}" install --with-statusline`)
  }
} else {
  console.warn(`\nWARNING: usage-report skill not found at ${usageSkill} — spend/usage-report disabled.`)
}

console.log('\nRunning pnpm install…')
const inst = spawnSync(process.platform === 'win32' ? 'pnpm.cmd' : 'pnpm', ['install'], { stdio: 'inherit' })
if (inst.status !== 0) process.exit(inst.status ?? 1)

console.log('\nRunning pnpm start (builds web, then serves on http://127.0.0.1:4317)…')
const start = spawnSync(process.platform === 'win32' ? 'pnpm.cmd' : 'pnpm', ['start'], { stdio: 'inherit' })
process.exit(start.status ?? 1)